import * as OpenAPI from 'fumadocs-openapi';
import matter from 'gray-matter';
import { rimrafSync } from 'rimraf';
import { mkdir, writeFile } from 'node:fs/promises';
import * as path from 'node:path';

const out = './content/docs/api-reference';

/** Remote spec used to refresh the on-disk snapshot (see ensureLocalOpenApiSpec). */
const OPENAPI_SPEC_URL = 'https://spec.speakeasy.com/novu/novu/json-development-with-code-samples';
/** Relative to repo root; must match resolveOpenApiDocument in src/app/[[...slug]]/page.tsx */
const OPENAPI_SPEC_RELATIVE = 'content/openapi/novu-spec.json';

/**
 * js-yaml (via gray-matter) may emit `description: |2-` with an explicit indent digit.
 * Keep a consistent `description: |-` literal block for all generated API pages.
 */
function normalizeDescriptionLiteralBlockIndicator(mdx) {
  if (!mdx.startsWith('---\n')) {
    return mdx;
  }
  const close = '\n---\n';
  const end = mdx.indexOf(close, 4);
  if (end === -1) {
    return mdx;
  }
  const yaml = mdx.slice(4, end);
  const body = mdx.slice(end);
  const normalized = yaml.replace(/^description: \|\d+([-+]?)\s*$/m, 'description: |-');
  if (normalized === yaml) {
    return mdx;
  }
  return `---\n${normalized}${body}`;
}

/**
 * Fumadocs OpenAPI puts the operation description into `_openapi.structuredData.contents`.
 * We keep the frontmatter `description` only and set `contents` to [] so it is not duplicated.
 * `fumadocs-core` requires `structuredData.contents` to be an iterable array (see mdx-plugins).
 * Descriptions are Markdown; the site renders them via `MarkdownDescription` (see `page.tsx`).
 */
function stripOpenapiStructuredDataContents(mdx) {
  if (!mdx.includes('_openapi:') || !mdx.includes('structuredData:')) {
    return normalizeDescriptionLiteralBlockIndicator(mdx);
  }
  try {
    const parsed = matter(mdx);
    const structuredData = parsed.data?._openapi?.structuredData;
    if (!structuredData) {
      return normalizeDescriptionLiteralBlockIndicator(mdx);
    }
    structuredData.contents = [];
    const out = matter.stringify(parsed.content, parsed.data, { lineWidth: -1 });
    return normalizeDescriptionLiteralBlockIndicator(out);
  } catch (err) {
    console.warn('stripOpenapiStructuredDataContents: skipped transform', err);
  }
  return normalizeDescriptionLiteralBlockIndicator(mdx);
}

// Helper function for slugifying
function slugify(text) {
  if (!text) return '';
  return text
    .toString()
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '-') // Replace spaces with -
    .replace(/[^\w-]+/g, '') // Remove all non-word chars
    .replace(/--+/g, '-'); // Replace multiple - with single -
}

async function ensureLocalOpenApiSpec() {
  const specPath = path.join(process.cwd(), OPENAPI_SPEC_RELATIVE);
  await mkdir(path.dirname(specPath), { recursive: true });
  const res = await fetch(OPENAPI_SPEC_URL);
  if (!res.ok) {
    throw new Error(`Failed to download OpenAPI spec (${res.status}): ${OPENAPI_SPEC_URL}`);
  }
  await writeFile(specPath, await res.text(), 'utf8');
  console.log(`Wrote OpenAPI snapshot: ${specPath}`);
}

async function main() {
  await ensureLocalOpenApiSpec();

  // clean generated files
  rimrafSync(out, {
    filter(v) {
      const relativePath = path.relative(out, v);
      return (
        !relativePath.endsWith('index.mdx') && // Preserves top-level index.mdx if any
        !relativePath.endsWith('overview.mdx') &&
        !relativePath.endsWith('rate-limiting.mdx') &&
        !relativePath.endsWith('payload-limits.mdx') &&
        !relativePath.endsWith('idempotency.mdx') &&
        !relativePath.endsWith('meta.json') &&
        !relativePath.endsWith('model.mdx') &&
        !relativePath.endsWith('api-types.ts')
      );
    },
  });

  const docsOutputPath = out; // './content/docs/api-reference'
  // Local file avoids per-navigation HTTP fetch + dereference of the full spec at runtime (see fumadocs-openapi processDocument).
  const openApiInput = OPENAPI_SPEC_RELATIVE;

  const pages = await OpenAPI.generatePages(openApiInput, {
    // Keep description in frontmatter only (Markdown). The page template renders it with GFM.
    includeDescription: false,
    addGeneratedComment:
      'This file was generated by scripts/generate-docs.mjs. Do not edit this file directly. Regenerate with pnpm run build:docs.',
    frontmatter: (title, description, context) => {
      return {
        title,
        description,
        context,
      };
    },
  });

  // Structure to hold metadata for each tag: Map<tagSlug, Record<operationSlug, operationTitle>>
  const tagsMeta = new Map();

  for (const page of pages) {
    if (page.type === 'operation' && page.operation.summary) {
      let tagName = 'unknown';
      if (page.operation.tags && page.operation.tags.length > 0) {
        tagName = page.operation.tags[0];
      }
      const tagSlug = slugify(tagName);

      const operationSummary = page.operation.summary; // Keep original summary for title
      const operationSummarySlug = slugify(operationSummary);

      if (!operationSummarySlug) {
        console.warn(
          `Skipping operation with empty slug from summary: ${operationSummary} (method: ${page.operation.method}, path: ${page.item.path})`
        );
        continue;
      }

      // Ensure the entry for this tag exists in tagsMeta
      if (!tagsMeta.has(tagSlug)) {
        tagsMeta.set(tagSlug, {});
      }

      // Add/update the operation's metadata for this tag
      const currentTagMeta = tagsMeta.get(tagSlug);
      currentTagMeta[operationSummarySlug] = operationSummary; // Map slug to original summary for title

      const relativeFilePath = path.join(tagSlug, `${operationSummarySlug}.mdx`);
      const absoluteFilePath = path.join(docsOutputPath, relativeFilePath);

      await mkdir(path.dirname(absoluteFilePath), { recursive: true });
      await writeFile(absoluteFilePath, stripOpenapiStructuredDataContents(page.content));
      console.log(`Generated MDX: ${absoluteFilePath}`);
    }
  }
}

main().catch(console.error);
